spring:
  datasource:
    url: ${DATABASE_URL:${DB_URL}}
    username: ${PGUSER:${DB_USERNAME}}
    password: ${PGPASSWORD:${DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver
#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: ${MAIL_TLS:true}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: false

  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8088/login/oauth2/code/google}
          scope:
            - email
            - profile

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  port: ${PORT}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  mail:
    from: ${MAIL_FROM}
    brevo:
      api-key: ${MAIL_PASSWORD}

logging:
  level:
    org.springframework.web: INFO
